/**
 * Public browser-side question bank for the zero-backend GitHub Pages edition.
 * Because GitHub Pages serves only public static files, answer keys cannot be
 * hidden from technically knowledgeable users. Use this edition for practice
 * or supervised low-stakes classroom activities, not secure examinations.
 */
const q = (id, difficulty, topic, stem, options, correctIndex, instructorComment, figure = null) => ({
  id, difficulty, topic, stem, options, correctIndex, instructorComment, ...(figure ? { figure } : {})
});

const questions = [
  // BASIC: 16 questions (20% of the 80-question bank)
  q("B001", "basic", "Hydrostatic equilibrium",
    "In the stellar-structure equation \\(\\frac{dP}{dr}=-\\frac{Gm(r)\\rho(r)}{r^2}\\), why is \\(dP/dr\\) negative?",
    ["Pressure decreases outward because gravity pulls matter inward", "Pressure increases outward because temperature rises", "Enclosed mass is negative", "Density must increase toward the surface"], 0,
    "With outward-positive radius, the inward gravitational force requires pressure to fall outward."),
  q("B002", "basic", "Mass conservation",
    "What does \\(\\frac{dm}{dr}=4\\pi r^2\\rho\\) state?",
    ["A thin spherical shell adds mass \\(4\\pi r^2\\rho\\,dr\\)", "Mass is converted to luminosity at this rate", "Density is constant throughout a star", "The stellar radius grows at a constant rate"], 0,
    "The mass of a shell of thickness dr is its volume, 4πr²dr, times density."),
  q("B003", "basic", "Energy generation",
    "If \\(\\epsilon\\) is the energy-generation rate per unit mass, which equation gives the luminosity gradient?",
    ["\\(dL/dr=4\\pi r^2\\rho\\epsilon\\)", "\\(dL/dr=-Gm\\rho/r^2\\)", "\\(dL/dr=4\\pi r^2/\\rho\\epsilon\\)", "\\(dL/dr=L/(4\\pi r^2)\\)"], 0,
    "A shell generates dL = ε dm = ερ4πr²dr."),
  q("B004", "basic", "Energy transport",
    "In a radiative stellar zone, energy is transported primarily by",
    ["repeated absorption, emission, and scattering of photons", "bulk overturning of macroscopic gas parcels", "thermal conduction by degenerate electrons only", "outward motion of the entire star"], 0,
    "Radiative diffusion is a photon random walk through interacting matter."),
  q("B005", "basic", "Equations of state",
    "Ignoring radiation pressure, the ideal-gas pressure of a fully ionized stellar plasma is",
    ["\\(P=\\rho k_{\\mathrm B}T/(\\mu m_{\\mathrm H})\\)", "\\(P=\\rho \\mu m_{\\mathrm H}/(k_{\\mathrm B}T)\\)", "\\(P=aT^4\\)", "\\(P=K\\rho^{-1}\\)"], 0,
    "The particle number density is ρ/(μm_H), so P = nk_BT."),
  q("B006", "basic", "Mean molecular weight",
    "For completely ionized pure hydrogen, what is the mean molecular weight \\(\\mu\\) per free particle?",
    ["\\(1/2\\)", "\\(1\\)", "\\(2\\)", "\\(4/3\\)"], 0,
    "Each hydrogen atom supplies one proton and one electron, giving two particles per m_H."),
  q("B007", "basic", "Virial theorem",
    "For a stable, non-relativistic ideal-gas star with negligible surface pressure, the scalar virial theorem is",
    ["\\(2U+\\Omega=0\\)", "\\(U+2\\Omega=0\\)", "\\(U=\\Omega\\)", "\\(U+\\Omega=0\\)"], 0,
    "Hydrostatic equilibrium gives 2U + Ω = 0 for a monatomic ideal gas, with Ω negative."),
  q("B008", "basic", "Stellar timescales",
    "The Kelvin–Helmholtz timescale \\(t_{\\mathrm{KH}}\\sim GM^2/(RL)\\) estimates how long a star could shine using",
    ["gravitational contraction", "hydrogen fusion", "radioactive decay", "rotation"], 0,
    "GM²/R is the scale of gravitational binding energy; dividing by luminosity gives the contraction-powered lifetime."),
  q("B009", "basic", "Stellar timescales",
    "The dynamical timescale \\(t_{\\mathrm{dyn}}\\sim\\sqrt{R^3/(GM)}\\) is closest to a star's",
    ["free-fall or global pressure-adjustment time", "main-sequence nuclear lifetime", "photon diffusion time", "galactic orbital period"], 0,
    "It is the characteristic free-fall/sound-crossing order of time for global hydrostatic readjustment."),
  q("B010", "basic", "Eddington luminosity",
    "For fixed opacity \\(\\kappa\\), the Eddington luminosity \\(L_{\\mathrm{Edd}}=4\\pi GMc/\\kappa\\) scales with mass as",
    ["\\(L_{\\mathrm{Edd}}\\propto M\\)", "\\(L_{\\mathrm{Edd}}\\propto M^2\\)", "\\(L_{\\mathrm{Edd}}\\propto M^{-1}\\)", "It is independent of mass"], 0,
    "All other quantities fixed, the expression is linear in M."),
  q("B011", "basic", "Convection",
    "According to the Schwarzschild criterion, a chemically homogeneous layer is convectively unstable when",
    ["\\(\\nabla_{\\mathrm{rad}}>\\nabla_{\\mathrm{ad}}\\)", "\\(\\nabla_{\\mathrm{rad}}<\\nabla_{\\mathrm{ad}}\\)", "\\(\\nabla_{\\mathrm{rad}}=0\\)", "\\(\\nabla_{\\mathrm{ad}}>1\\)"], 0,
    "A displaced parcel remains warmer and less dense when the required radiative gradient exceeds the adiabatic gradient."),
  q("B012", "basic", "Polytropes",
    "A polytropic equation of state is written",
    ["\\(P=K\\rho^{1+1/n}\\)", "\\(P=K\\rho^{1-n}\\)", "\\(P=K/\\rho^n\\)", "\\(P=K+n\\rho\\)"], 0,
    "The polytropic exponent is γ = 1 + 1/n."),
  q("B013", "basic", "Hydrogen burning",
    "What is the net result of a complete proton–proton chain?",
    ["\\(4p\\rightarrow{}^4\\mathrm{He}+2e^++2\\nu_e+\\text{energy}\\)", "\\(3\\alpha\\rightarrow{}^{12}\\mathrm C\\)", "\\(p+{}^{12}\\mathrm C\\rightarrow{}^{13}\\mathrm N\\) only", "\\({}^{4}\\mathrm{He}\\rightarrow4p\\)"], 0,
    "Four protons ultimately form one helium-4 nucleus, with positrons, neutrinos, and released energy."),
  q("B014", "basic", "Hydrogen burning",
    "In the CNO cycle, carbon, nitrogen, and oxygen nuclei mainly act as",
    ["catalysts for converting hydrogen into helium", "the final ash consumed in every cycle", "sources of electron degeneracy", "opacity-free coolants"], 0,
    "The catalytic nuclei are regenerated after a complete CNO-I cycle."),
  q("B015", "basic", "Helium burning",
    "The triple-alpha reaction primarily produces",
    ["carbon-12", "oxygen-16 directly from three alpha particles", "neon-20", "iron-56"], 0,
    "Three alpha particles combine through the 8Be resonance pathway to form 12C."),
  q("B016", "basic", "Hertzsprung–Russell diagram",
    "On the conventional Hertzsprung–Russell diagram, stellar effective temperature generally",
    ["decreases from left to right", "increases from left to right", "is plotted only on the vertical axis", "is constant along the main sequence"], 0,
    "The horizontal axis is conventionally reversed: hot stars are left and cool stars are right.",
    { type: "hr-diagram", alt: "Schematic H–R diagram with a descending main sequence", points: [{x:125,y:65,label:"Hot, luminous"},{x:465,y:218,label:"Cool, faint"}] }),

  // INTERMEDIATE: 40 questions (50% of the bank)
  q("I001", "intermediate", "Hydrostatic equilibrium",
    "At radius \\(r\\), a layer has \\(m=1.0\\times10^{30}\\,\\mathrm{kg}\\), \\(\\rho=100\\,\\mathrm{kg\\,m^{-3}}\\), and \\(r=5.0\\times10^8\\,\\mathrm m\\). Using \\(G=6.67\\times10^{-11}\\,\\mathrm{SI}\\), what is \\(dP/dr\\)?",
    ["\\(-2.67\\times10^{-5}\\,\\mathrm{Pa\\,m^{-1}}\\)", "\\(-2.67\\times10^{4}\\,\\mathrm{Pa\\,m^{-1}}\\)", "\\(+2.67\\times10^{-5}\\,\\mathrm{Pa\\,m^{-1}}\\)", "\\(-1.33\\times10^{-7}\\,\\mathrm{Pa\\,m^{-1}}\\)"], 1,
    "−Gmρ/r² = −(6.67×10⁻¹¹)(10³⁰)(100)/(2.5×10¹⁷) = −2.67×10⁴ Pa m⁻¹."),
  q("I002", "intermediate", "Mass conservation",
    "Near the centre of a star the density is approximately constant at \\(\\rho_c\\). What is the leading behaviour of enclosed mass?",
    ["\\(m(r)\\simeq(4\\pi/3)\\rho_c r^3\\)", "\\(m(r)\\simeq4\\pi\\rho_c r^2\\)", "\\(m(r)\\simeq\\rho_c/r\\)", "\\(m(r)\\simeq M-r\\)"], 0,
    "Integrating dm/dr = 4πr²ρ_c from 0 to r gives (4π/3)ρ_cr³."),
  q("I003", "intermediate", "Central conditions",
    "A dimensional estimate of the central pressure of a star of mass \\(M\\) and radius \\(R\\) is",
    ["\\(P_c\\sim GM^2/R^4\\)", "\\(P_c\\sim GM/R^2\\)", "\\(P_c\\sim GM^2/R\\)", "\\(P_c\\sim MR^2/G\\)"], 0,
    "Hydrostatic balance gives P/R ∼ GMρ/R² with ρ ∼ M/R³, hence P_c ∼ GM²/R⁴."),
  q("I004", "intermediate", "Energy generation",
    "A shell has \\(r=1.0\\times10^8\\,\\mathrm m\\), thickness \\(dr=1.0\\times10^6\\,\\mathrm m\\), \\(\\rho=10^5\\,\\mathrm{kg\\,m^{-3}}\\), and \\(\\epsilon=2.0\\times10^{-4}\\,\\mathrm{W\\,kg^{-1}}\\). Its generated luminosity is approximately",
    ["\\(2.51\\times10^{24}\\,\\mathrm W\\)", "\\(2.51\\times10^{18}\\,\\mathrm W\\)", "\\(1.26\\times10^{22}\\,\\mathrm W\\)", "\\(2.00\\times10^{17}\\,\\mathrm W\\)"], 0,
    "dL = 4πr²ρ ε dr = 4π(10¹⁶)(10⁵)(2×10⁻⁴)(10⁶) = 2.51×10²⁴ W."),
  q("I005", "intermediate", "Radiative transport",
    "From \\(dT/dr=-3\\kappa\\rho L/(16\\pi acT^3r^2)\\), which change alone makes the magnitude of the radiative temperature gradient larger?",
    ["Increasing opacity", "Increasing temperature", "Increasing radius", "Decreasing luminosity"], 0,
    "The magnitude is directly proportional to κ, ρ, and L, and inversely proportional to T³ and r²."),
  q("I006", "intermediate", "Radiative transport",
    "Why does a large opacity tend to promote convection?",
    ["Radiation then requires a steeper temperature gradient to carry the luminosity", "Photons become more massive and sink", "The adiabatic gradient always becomes zero", "Nuclear reactions cease immediately"], 0,
    "A larger κ increases ∇rad; if it exceeds ∇ad, radiative equilibrium is unstable to convection."),
  q("I007", "intermediate", "Equations of state",
    "For \\(\\rho=1.0\\times10^5\\,\\mathrm{kg\\,m^{-3}}\\), \\(T=1.5\\times10^7\\,\\mathrm K\\), and \\(\\mu=0.60\\), estimate ideal-gas pressure using \\(k_B=1.38\\times10^{-23}\\,\\mathrm{J\\,K^{-1}}\\) and \\(m_H=1.67\\times10^{-27}\\,\\mathrm{kg}\\).",
    ["\\(2.07\\times10^{16}\\,\\mathrm{Pa}\\)", "\\(2.07\\times10^{11}\\,\\mathrm{Pa}\\)", "\\(1.24\\times10^{16}\\,\\mathrm{Pa}\\)", "\\(3.45\\times10^{8}\\,\\mathrm{Pa}\\)"], 0,
    "ρkT/(μm_H) = 10⁵·1.38×10⁻²³·1.5×10⁷/(0.60·1.67×10⁻²⁷) = 2.07×10¹⁶ Pa."),
  q("I008", "intermediate", "Radiation pressure",
    "At \\(T=2.0\\times10^7\\,\\mathrm K\\), estimate \\(P_{\\rm rad}=aT^4/3\\) using \\(a=7.57\\times10^{-16}\\,\\mathrm{J\\,m^{-3}\\,K^{-4}}\\).",
    ["\\(4.04\\times10^{13}\\,\\mathrm{Pa}\\)", "\\(4.04\\times10^{12}\\,\\mathrm{Pa}\\)", "\\(1.21\\times10^{14}\\,\\mathrm{Pa}\\)", "\\(5.05\\times10^5\\,\\mathrm{Pa}\\)"], 0,
    "T⁴ = 1.6×10²⁹ K⁴, so aT⁴/3 = 4.04×10¹³ Pa."),
  q("I009", "intermediate", "Mean molecular weight",
    "For a fully ionized mixture with mass fractions \\(X=0.70\\), \\(Y=0.28\\), and \\(Z=0.02\\), use \\(\\mu^{-1}\\simeq2X+3Y/4+Z/2\\). What is \\(\\mu\\)?",
    ["0.617", "1.62", "0.500", "0.280"], 0,
    "μ⁻¹ = 1.40 + 0.21 + 0.01 = 1.62, hence μ = 0.617."),
  q("I010", "intermediate", "Virial theorem",
    "A contracting ideal-gas protostar releases gravitational energy \\(\\Delta E_g<0\\). Approximately what fraction of \\(|\\Delta E_g|\\) is radiated while the rest heats the gas?",
    ["One half", "All of it", "One quarter", "None of it"], 0,
    "The virial theorem implies half the released gravitational energy raises internal energy and half is radiated."),
  q("I011", "intermediate", "Stellar timescales",
    "Using solar units, \\(t_{\\mathrm{KH}}\\approx3.1\\times10^7(M/M_\\odot)^2[(R/R_\\odot)(L/L_\\odot)]^{-1}\\,\\mathrm{yr}\\). Estimate it for \\(M=2M_\\odot\\), \\(R=2R_\\odot\\), \\(L=16L_\\odot\\).",
    ["\\(3.9\\times10^6\\,\\mathrm{yr}\\)", "\\(3.1\\times10^7\\,\\mathrm{yr}\\)", "\\(6.2\\times10^7\\,\\mathrm{yr}\\)", "\\(9.7\\times10^5\\,\\mathrm{yr}\\)"], 0,
    "Scale factor = 2²/(2·16) = 1/8, so t_KH ≈ 3.9×10⁶ yr."),
  q("I012", "intermediate", "Stellar timescales",
    "If a family of stars has approximately constant mean density, how does \\(t_{\\mathrm{dyn}}\\sim(R^3/GM)^{1/2}\\) vary across the family?",
    ["It is approximately constant", "It is proportional to mass", "It is proportional to radius", "It is inversely proportional to luminosity"], 0,
    "Since M/R³ is constant, R³/M and therefore t_dyn are constant."),
  q("I013", "intermediate", "Stellar lifetimes",
    "Assume \\(L\\propto M^{3.5}\\) and available main-sequence fuel \\(\\propto M\\). Then \\(t_{\\rm MS}\\) scales approximately as",
    ["\\(M^{-2.5}\\)", "\\(M^{2.5}\\)", "\\(M^{-3.5}\\)", "\\(M^{1.0}\\)"], 0,
    "Lifetime ∼ fuel/luminosity ∝ M/M³·⁵ = M⁻²·⁵."),
  q("I014", "intermediate", "Stellar lifetimes",
    "With \\(t_{\\rm MS}\\approx10^{10}(M/M_\\odot)^{-2.5}\\,\\mathrm{yr}\\), the main-sequence lifetime of a \\(2M_\\odot\\) star is closest to",
    ["\\(1.8\\times10^9\\,\\mathrm{yr}\\)", "\\(5.7\\times10^9\\,\\mathrm{yr}\\)", "\\(3.2\\times10^8\\,\\mathrm{yr}\\)", "\\(2.5\\times10^{10}\\,\\mathrm{yr}\\)"], 0,
    "2⁻²·⁵ = 1/5.657, giving 1.77×10⁹ yr."),
  q("I015", "intermediate", "Eddington luminosity",
    "For electron-scattering opacity \\(\\kappa=0.034\\,\\mathrm{m^2\\,kg^{-1}}\\), \\(L_{\\rm Edd}\\approx1.47\\times10^{31}(M/M_\\odot)\\,\\mathrm W\\). What is it for \\(10M_\\odot\\)?",
    ["\\(1.47\\times10^{32}\\,\\mathrm W\\)", "\\(1.47\\times10^{31}\\,\\mathrm W\\)", "\\(1.47\\times10^{33}\\,\\mathrm W\\)", "\\(1.47\\times10^{30}\\,\\mathrm W\\)"], 0,
    "The Eddington luminosity is linear in mass for fixed opacity."),
  q("I016", "intermediate", "Opacity",
    "In a fully ionized hot stellar interior, electron-scattering opacity is approximately independent of",
    ["temperature and density", "chemical composition", "the electron abundance per unit mass", "ionization state"], 0,
    "Once fully ionized, Thomson scattering per unit mass is nearly independent of T and ρ but retains composition dependence."),
  q("I017", "intermediate", "Convection",
    "For a monatomic ideal gas, \\(\\nabla_{\\rm ad}=(\\partial\\ln T/\\partial\\ln P)_S\\) is",
    ["\\(2/5\\)", "\\(3/5\\)", "\\(1/4\\)", "\\(1\\)"], 0,
    "For γ = 5/3, ∇ad = (γ−1)/γ = 2/5."),
  q("I018", "intermediate", "Convection",
    "A layer has \\(\\nabla_{\\rm rad}=0.46\\) and \\(\\nabla_{\\rm ad}=0.40\\), with uniform composition. It is",
    ["convectively unstable", "stable against convection", "necessarily electron-degenerate", "exactly isothermal"], 0,
    "Because ∇rad > ∇ad, the Schwarzschild criterion predicts instability."),
  q("I019", "intermediate", "Polytropes",
    "Which polytropic index represents a non-relativistic, completely degenerate electron gas?",
    ["\\(n=3/2\\)", "\\(n=3\\)", "\\(n=1\\)", "\\(n=5\\)"], 0,
    "Non-relativistic degeneracy gives P ∝ ρ⁵ᐟ³, so 1 + 1/n = 5/3 and n = 3/2."),
  q("I020", "intermediate", "Polytropes",
    "Which polytropic index corresponds to an ultra-relativistic degenerate electron gas or a radiation-pressure-dominated configuration?",
    ["\\(n=3\\)", "\\(n=3/2\\)", "\\(n=0\\)", "\\(n=1\\)"], 0,
    "Both have P ∝ ρ⁴ᐟ³, implying n = 3."),
  q("I021", "intermediate", "Lane–Emden equation",
    "For \\(n=0\\), the Lane–Emden solution satisfying \\(\\theta(0)=1\\), \\(\\theta'(0)=0\\) is",
    ["\\(\\theta=1-\\xi^2/6\\)", "\\(\\theta=\\sin\\xi/\\xi\\)", "\\(\\theta=e^{-\\xi}\\)", "\\(\\theta=(1+\\xi^2/3)^{-1/2}\\)"], 0,
    "Direct integration of (1/ξ²)d/dξ(ξ²θ′) = −1 gives θ = 1 − ξ²/6."),
  q("I022", "intermediate", "Lane–Emden equation",
    "The first zero \\(\\xi_1\\) of a finite-radius Lane–Emden solution identifies",
    ["the stellar surface where the model density vanishes", "the centre where enclosed mass vanishes", "the radius of maximum temperature", "the nuclear-burning boundary in every star"], 0,
    "Since ρ = ρ_c θⁿ, the first zero of θ sets the polytrope's surface."),
  q("I023", "intermediate", "Hydrogen burning",
    "The initial reaction \\(p+p\\rightarrow d+e^++\\nu_e\\) makes the pp chain slow mainly because it",
    ["requires a weak-interaction conversion of a proton to a neutron", "has no Coulomb barrier", "requires carbon as a catalyst", "absorbs more energy than the chain releases"], 0,
    "The beta-plus weak interaction is much slower than strong or electromagnetic nuclear reactions."),
  q("I024", "intermediate", "Hydrogen burning",
    "Near the solar central temperature, a useful local scaling is roughly \\(\\epsilon_{pp}\\propto T^4\\). If temperature rises by 5% at fixed density and composition, \\(\\epsilon_{pp}\\) changes by about",
    ["22% increase", "5% increase", "46% increase", "20% decrease"], 0,
    "1.05⁴ = 1.216, a 21.6% increase."),
  q("I025", "intermediate", "CNO cycle",
    "If locally \\(\\epsilon_{CNO}\\propto T^{17}\\), a 2% temperature rise changes the rate by approximately",
    ["40% increase", "2% increase", "17% increase", "40% decrease"], 0,
    "1.02¹⁷ ≈ 1.40, so the increase is about 40%."),
  q("I026", "intermediate", "Hydrogen burning",
    "Compared with the Sun, a sufficiently massive main-sequence star usually has a convective core because",
    ["strongly temperature-sensitive CNO burning produces a steep radiative gradient", "electron degeneracy dominates its centre", "hydrogen burning occurs only at its surface", "its opacity is exactly zero"], 0,
    "Centrally concentrated CNO energy generation raises ∇rad and drives core convection."),
  q("I027", "intermediate", "Helium burning",
    "Why is the \\(7.65\\,\\mathrm{MeV}\\) Hoyle state important?",
    ["It resonantly enhances formation of carbon-12 in the triple-alpha reaction", "It prevents helium burning", "It sets the Chandrasekhar mass", "It initiates the pp chain"], 0,
    "The excited 12C state lies near the 8Be+α energy and greatly increases the triple-alpha rate."),
  q("I028", "intermediate", "Main-sequence evolution",
    "As hydrogen is converted to helium in a solar-type main-sequence core, the mean molecular weight rises. The core generally responds by",
    ["contracting and heating while luminosity slowly increases", "expanding and cooling until fusion stops immediately", "becoming less dense at constant temperature", "moving the star directly to the white-dwarf sequence"], 0,
    "Higher μ reduces particles per unit mass; hydrostatic/thermal readjustment leads to hotter contraction and rising luminosity."),
  q("I029", "intermediate", "Pre-main-sequence evolution",
    "A low-mass pre-main-sequence star descending the Hayashi track is approximately",
    ["fully convective with nearly constant effective temperature", "fully radiative with constant luminosity", "supported by electron degeneracy", "burning carbon in its core"], 0,
    "Hayashi-track stars are largely convective and contract at nearly fixed T_eff, moving downward in luminosity."),
  q("I030", "intermediate", "Pre-main-sequence evolution",
    "Deuterium burning in a protostar is important because it",
    ["temporarily moderates contraction as a thermostat", "provides the star's entire main-sequence lifetime", "requires a degenerate carbon core", "always disrupts the protostar"], 0,
    "Deuterium ignites near 10⁶ K and its strong temperature response temporarily regulates contraction."),
  q("I031", "intermediate", "Red-giant evolution",
    "After central hydrogen exhaustion in a low-mass star, hydrogen burning continues mainly",
    ["in a shell around an inert helium core", "uniformly throughout the entire star", "in the photosphere", "inside a carbon–oxygen core"], 0,
    "The helium core contracts while hydrogen shell burning powers the subgiant/red-giant luminosity."),
  q("I032", "intermediate", "Helium flash",
    "Why does core helium ignition become a flash in a low-mass red giant?",
    ["Degenerate pressure is initially insensitive to temperature, delaying expansion feedback", "Radiation pressure instantly removes the core", "The core contains no helium", "The CNO cycle becomes endothermic"], 0,
    "Heating does not initially expand and cool a degenerate core, so the temperature-sensitive triple-alpha rate runs away until degeneracy lifts."),
  q("I033", "intermediate", "Horizontal branch",
    "A horizontal-branch star is powered primarily by",
    ["core helium burning plus a hydrogen-burning shell", "core hydrogen burning only", "gravitational contraction only", "carbon burning in a degenerate core"], 0,
    "Stable core He burning and a surrounding H-burning shell characterize horizontal-branch stars."),
  q("I034", "intermediate", "Degenerate matter",
    "At zero temperature, electron degeneracy pressure arises from",
    ["the Pauli exclusion principle filling momentum states", "thermal collisions alone", "radiation absorption by ions", "nuclear binding energy"], 0,
    "Fermions fill states up to the Fermi momentum, producing pressure even as T approaches zero."),
  q("I035", "intermediate", "White dwarfs",
    "For a non-relativistic degenerate white dwarf of fixed composition, increasing its mass generally makes its radius",
    ["smaller", "larger", "unchanged", "equal to its Schwarzschild radius"], 0,
    "The approximate non-relativistic mass–radius relation is R ∝ M⁻¹ᐟ³."),
  q("I036", "intermediate", "Chandrasekhar mass",
    "For electron mean molecular weight \\(\\mu_e=2\\), the Chandrasekhar mass is closest to",
    ["\\(1.44M_\\odot\\)", "\\(0.14M_\\odot\\)", "\\(5.8M_\\odot\\)", "\\(10M_\\odot\\)"], 0,
    "M_Ch ≈ 5.83/μ_e² M_sun = 1.46 M_sun (commonly quoted near 1.44)."),
  q("I037", "intermediate", "Supernovae",
    "A classical single-degenerate Type Ia supernova scenario involves",
    ["a carbon–oxygen white dwarf gaining mass from a companion and undergoing thermonuclear runaway", "iron-core collapse of an isolated red supergiant", "helium fusion in a brown dwarf", "planet–planet collision"], 0,
    "A CO white dwarf in a binary may approach conditions for explosive carbon burning; Type Ia spectra lack hydrogen."),
  q("I038", "intermediate", "Massive-star evolution",
    "Why does hydrostatic fusion in a massive star not produce net energy beyond the iron group?",
    ["Fusion beyond the binding-energy peak is endothermic", "Iron has no protons", "The core temperature becomes zero", "Electron scattering opacity vanishes"], 0,
    "Nuclei near iron have maximal binding energy per nucleon, so further fusion requires energy."),
  q("I039", "intermediate", "Star clusters",
    "A cluster's main-sequence turn-off is most directly used to estimate its",
    ["age", "distance only", "total angular momentum", "metal abundance only"], 0,
    "The turn-off mass has a main-sequence lifetime approximately equal to the cluster age."),
  q("I040", "intermediate", "Binary evolution",
    "Roche-lobe overflow begins when",
    ["a star expands to fill its Roche lobe", "both stars reach the Eddington luminosity", "the binary becomes unbound", "the orbital eccentricity is exactly zero"], 0,
    "At the Roche surface, gas near the inner Lagrange point can flow to the companion."),

  // ADVANCED: 24 questions (30% of the bank)
  q("A001", "advanced", "Hydrostatic equilibrium",
    "Near the centre, take \\(\\rho\\simeq\\rho_c\\) and \\(m(r)\\simeq(4\\pi/3)\\rho_c r^3\\). Which expansion satisfies hydrostatic equilibrium to order \\(r^2\\)?",
    ["\\(P(r)\\simeq P_c-(2\\pi/3)G\\rho_c^2r^2\\)", "\\(P(r)\\simeq P_c-(4\\pi/3)G\\rho_c^2r\\)", "\\(P(r)\\simeq P_c+(2\\pi/3)G\\rho_c^2r^2\\)", "\\(P(r)\\simeq P_c-G\\rho_c/r\\)"], 0,
    "Substitution gives dP/dr = −(4π/3)Gρ_c²r; integration supplies −(2π/3)Gρ_c²r²."),
  q("A002", "advanced", "Energy generation",
    "In an advanced burning core, let \\(\\epsilon=\\epsilon_{\\rm nuc}-\\epsilon_\\nu\\), including neutrino losses. If \\(\\epsilon_\\nu>\\epsilon_{\\rm nuc}\\) throughout a shell, then",
    ["\\(dL/dr<0\\) across that shell", "\\(dL/dr>0\\) necessarily", "hydrostatic equilibrium must fail instantly", "the opacity must be negative"], 0,
    "With net ε < 0, dL/dr = 4πr²ρε is negative; luminosity decreases outward across the energy-losing shell."),
  q("A003", "advanced", "Radiative transport",
    "Combining hydrostatic equilibrium with radiative diffusion gives the dimensionless radiative gradient",
    ["\\(\\nabla_{\\rm rad}=\\frac{3\\kappa LP}{16\\pi acGmT^4}\\)", "\\(\\nabla_{\\rm rad}=\\frac{16\\pi acGmT^4}{3\\kappa LP}\\)", "\\(\\nabla_{\\rm rad}=\\frac{3\\kappa L\\rho}{16\\pi acT^3r^2}\\)", "\\(\\nabla_{\\rm rad}=\\frac{Gm\\rho}{Pr}\\)"], 0,
    "Taking (d ln T/d ln P) = (P/T)(dT/dr)/(dP/dr) cancels ρ and r², yielding the stated expression."),
  q("A004", "advanced", "Radiation pressure",
    "At \\(T=1.0\\times10^8\\,\\mathrm K\\) and \\(\\mu=0.62\\), at what density are ideal-gas and radiation pressures equal? Use \\(a=7.57\\times10^{-16}\\,\\mathrm{J\\,m^{-3}K^{-4}}\\), \\(k_B=1.38\\times10^{-23}\\,\\mathrm{J\\,K^{-1}}\\), and \\(m_H=1.67\\times10^{-27}\\,\\mathrm{kg}\\).",
    ["\\(1.90\\times10^4\\,\\mathrm{kg\\,m^{-3}}\\)", "\\(1.90\\times10^8\\,\\mathrm{kg\\,m^{-3}}\\)", "\\(6.20\\times10^2\\,\\mathrm{kg\\,m^{-3}}\\)", "\\(2.52\\times10^{16}\\,\\mathrm{kg\\,m^{-3}}\\)"], 0,
    "Equating ρkT/(μm_H) = aT⁴/3 gives ρ = aμm_HT³/(3k) = 1.90×10⁴ kg m⁻³."),
  q("A005", "advanced", "Convection",
    "For a composition gradient, the Ledoux criterion for instability can be written \\(\\nabla_{\\rm rad}>\\nabla_{\\rm ad}+(\\varphi/\\delta)\\nabla_\\mu\\). A positive inward increase of mean molecular weight generally",
    ["stabilizes the layer relative to the Schwarzschild criterion", "destabilizes the layer in every case", "eliminates buoyancy", "forces \\(\\nabla_{\\rm ad}=0\\)"], 0,
    "A stabilizing μ gradient adds a positive term to the threshold required for convective instability."),
  q("A006", "advanced", "Polytropes",
    "For an \\(n=3\\) polytrope with fixed \\(K\\), the total mass is independent of central density. This property underlies",
    ["the existence of a limiting mass for relativistically degenerate white dwarfs", "the constant radius of all main-sequence stars", "the Hayashi forbidden zone", "the pp-chain branching ratio"], 0,
    "The n=3 mass scales as K^(3/2) but as ρ_c^0, producing the Chandrasekhar limiting-mass behaviour."),
  q("A007", "advanced", "Lane–Emden equation",
    "For \\(n=1\\), \\(\\theta(\\xi)=\\sin\\xi/\\xi\\). The dimensionless surface and dimensionless mass coefficient \\(-\\xi_1^2\\theta'(\\xi_1)\\) are",
    ["\\(\\xi_1=\\pi\\) and coefficient \\(=\\pi\\)", "\\(\\xi_1=1\\) and coefficient \\(=1\\)", "\\(\\xi_1=\\sqrt6\\) and coefficient \\(=2\\sqrt6\\)", "\\(\\xi_1=\\pi/2\\) and coefficient \\(=0\\)"], 0,
    "The first zero is π; θ′(π)=−1/π, so −π²θ′(π)=π."),
  q("A008", "advanced", "Polytropes",
    "The mass–radius relation for a polytrope of fixed \\(K\\), \\(n\\ne3\\), is \\(R\\propto M^{(1-n)/(3-n)}\\). For \\(n=3/2\\), this gives",
    ["\\(R\\propto M^{-1/3}\\)", "\\(R\\propto M^{1/3}\\)", "\\(R\\propto M^{-1}\\)", "\\(R\\propto M^0\\)"], 0,
    "(1−1.5)/(3−1.5)=−0.5/1.5=−1/3, the familiar non-relativistic white-dwarf scaling."),
  q("A009", "advanced", "Stellar homology",
    "Suppose a stellar model is homologously compressed so its radius halves at fixed mass while its dimensionless density profile is unchanged. How do characteristic density and pressure scales change?",
    ["\\(\\rho\\) rises by 8 and \\(P\\) rises by 16", "\\(\\rho\\) rises by 2 and \\(P\\) rises by 4", "\\(\\rho\\) rises by 4 and \\(P\\) rises by 8", "Both remain unchanged"], 0,
    "ρ ∼ M/R³ increases by 2³=8; P ∼ GM²/R⁴ increases by 2⁴=16."),
  q("A010", "advanced", "Eddington luminosity",
    "At fixed stellar mass, an opacity enhancement from \\(0.034\\) to \\(0.068\\,\\mathrm{m^2\\,kg^{-1}}\\) changes the local Eddington luminosity by",
    ["a factor of \\(1/2\\)", "a factor of 2", "a factor of 4", "no change"], 0,
    "L_Edd ∝ κ⁻¹; doubling opacity halves the Eddington luminosity."),
  q("A011", "advanced", "Degenerate matter",
    "The electron Fermi momentum is \\(p_F=\\hbar(3\\pi^2n_e)^{1/3}\\). If electron number density increases by a factor of 64, \\(p_F\\) increases by",
    ["a factor of 4", "a factor of 8", "a factor of 64", "a factor of 2"], 0,
    "p_F ∝ n_e^(1/3), and 64^(1/3)=4."),
  q("A012", "advanced", "Chandrasekhar mass",
    "Using \\(M_{\\rm Ch}\\simeq5.83\\mu_e^{-2}M_\\odot\\), estimate the limiting mass for material with \\(\\mu_e=2.15\\).",
    ["\\(1.26M_\\odot\\)", "\\(1.46M_\\odot\\)", "\\(2.71M_\\odot\\)", "\\(0.59M_\\odot\\)"], 0,
    "5.83/(2.15)² = 1.26."),
  q("A013", "advanced", "White dwarfs",
    "Estimate the gravitational redshift as an equivalent velocity, \\(v_g\\simeq GM/(Rc)\\), for a \\(0.60M_\\odot\\) white dwarf of radius \\(0.012R_\\odot\\). Use \\(G=6.67\\times10^{-11}\\), \\(M_\\odot=1.99\\times10^{30}\\,\\mathrm{kg}\\), \\(R_\\odot=6.96\\times10^8\\,\\mathrm m\\), and \\(c=3.00\\times10^8\\,\\mathrm{m\\,s^{-1}}\\).",
    ["\\(31.8\\,\\mathrm{km\\,s^{-1}}\\)", "\\(3.18\\,\\mathrm{km\\,s^{-1}}\\)", "\\(318\\,\\mathrm{km\\,s^{-1}}\\)", "\\(0.318\\,\\mathrm{km\\,s^{-1}}\\)"], 0,
    "GM/(Rc) = 3.18×10⁴ m s⁻¹ = 31.8 km s⁻¹."),
  q("A014", "advanced", "Neutron stars",
    "Why can a Newtonian hydrostatic equation not reliably determine the maximum neutron-star mass?",
    ["General-relativistic gravity and the high-density equation of state are essential", "Neutron stars contain no pressure", "Their masses are exactly zero in Newtonian theory", "Only radiative opacity determines their structure"], 0,
    "Compactness is large, requiring the Tolman–Oppenheimer–Volkoff equation, and the supranuclear EOS controls support."),
  q("A015", "advanced", "Helium flash",
    "Near helium ignition, approximate \\(\\epsilon_{3\\alpha}\\propto\\rho^2T^{40}\\). At fixed density, a 1% temperature increase changes the rate by approximately",
    ["49% increase", "1% increase", "40% increase", "149% increase"], 0,
    "1.01⁴⁰ ≈ 1.489, so the rate rises by about 49%."),
  q("A016", "advanced", "Red-giant evolution",
    "The steep core-mass–luminosity relation on the low-mass red-giant branch is chiefly associated with",
    ["a thin hydrogen-burning shell surrounding a degenerate, nearly isothermal helium core", "uniform hydrogen burning throughout a convective core", "carbon burning at the photosphere", "a declining helium-core mass"], 0,
    "Thin-shell homology around a compact degenerate core makes shell temperature and luminosity strongly dependent on core mass."),
  q("A017", "advanced", "Horizontal branch",
    "Two old globular clusters have similar metallicity but markedly different horizontal-branch morphologies. This illustrates",
    ["the horizontal-branch second-parameter problem", "the Chandrasekhar instability", "the Eddington standard model", "the Vogt–Russell theorem as an exact uniqueness proof"], 0,
    "Metallicity is the first parameter, but age, helium, mass loss, or other properties can act as a second parameter."),
  q("A018", "advanced", "Post-main-sequence evolution",
    "The Schönberg–Chandrasekhar limit is approximately \\(M_c/M\\lesssim0.37(\\mu_{\\rm env}/\\mu_c)^2\\). For \\(\\mu_{\\rm env}=0.62\\) and \\(\\mu_c=1.34\\), the limit is closest to",
    ["0.079", "0.171", "0.370", "0.730"], 0,
    "0.37(0.62/1.34)² = 0.079. Above this, an isothermal core cannot support the envelope in this approximation."),
  q("A019", "advanced", "Massive-star evolution",
    "In a pair-instability event, production of electron–positron pairs destabilizes the core primarily because it",
    ["reduces the effective adiabatic exponent below \\(4/3\\)", "raises electron degeneracy pressure without limit", "turns iron fusion exothermic", "removes all photons without changing pressure"], 0,
    "Photon energy diverted into pair rest mass softens the equation of state, so Γ₁ can fall below the dynamical-stability threshold."),
  q("A020", "advanced", "Core-collapse supernovae",
    "During collapse of an iron core, photodisintegration accelerates collapse because it",
    ["absorbs thermal energy and reduces pressure support", "releases fusion energy from iron", "immediately halts electron capture", "increases the adiabatic exponent far above \\(4/3\\)"], 0,
    "Breaking iron-group nuclei into alpha particles and nucleons is endothermic and drains pressure-supporting thermal energy."),
  q("A021", "advanced", "Star clusters",
    "A cluster has turn-off mass \\(1.5M_\\odot\\). Using \\(t_{\\rm MS}=10\\,\\mathrm{Gyr}(M/M_\\odot)^{-2.5}\\), estimate its age.",
    ["\\(3.63\\,\\mathrm{Gyr}\\)", "\\(6.67\\,\\mathrm{Gyr}\\)", "\\(1.78\\,\\mathrm{Gyr}\\)", "\\(27.6\\,\\mathrm{Gyr}\\)"], 0,
    "1.5²·⁵ = 2.756, hence 10/2.756 = 3.63 Gyr."),
  q("A022", "advanced", "Binary evolution",
    "For conservative mass transfer with constant total mass and orbital angular momentum, \\(a\\propto(M_1M_2)^{-2}\\). If masses change from \\((3,1)M_\\odot\\) to \\((2,2)M_\\odot\\), then \\(a_f/a_i\\) is",
    ["\\(9/16\\)", "\\(16/9\\)", "\\(3/4\\)", "\\(4/3\\)"], 0,
    "a_f/a_i = [(3·1)/(2·2)]² = (3/4)² = 9/16."),
  q("A023", "advanced", "Binary evolution",
    "In the common-envelope energy formalism, the parameter \\(\\alpha_{\\rm CE}\\) measures",
    ["the efficiency with which released orbital energy ejects the envelope", "the fraction of hydrogen burned by the pp chain", "the electron degeneracy parameter", "the ratio of stellar to Eddington luminosity"], 0,
    "The α formalism equates a fraction of the orbital-energy change to the envelope binding energy."),
  q("A024", "advanced", "Hertzsprung–Russell diagram",
    "The schematic track moves from point A (hotter, modest luminosity) to point B (cooler, much more luminous) after central hydrogen exhaustion. Which structural change best explains this motion?",
    ["Core contraction with hydrogen-shell burning and strong envelope expansion", "Uniform core hydrogen replenishment with envelope contraction", "Immediate formation of a cold white dwarf", "A decrease of radius at fixed luminosity"], 0,
    "Post-main-sequence core contraction heats the shell, while the envelope expands and cools, moving the star toward the red-giant region.",
    { type: "hr-diagram", alt: "Schematic post-main-sequence track from A toward the red-giant region B", path: "M145 205 C210 195, 250 120, 400 72", points: [{x:145,y:205,label:"A"},{x:400,y:72,label:"B",color:"#ffc966"}] })
];

export { questions };
