# Jekyll configuration file

# Theme selection
theme: jekyll-theme-cayman

# Enable dark mode
theme_config:
  dark_mode: true  # Set to true to enable dark mode

  # Custom navbar settings
  navbar_background: "#003366"  # Dark blue color for the navbar background

  # Hero section settings
  hero_background: url("opo0432d.jpg")  # Space-themed image as background
  hero_text_color: "#fff"  # White text color for better contrast on the hero image

# Site settings
title: "Nitesh's Research"
description: "Machine Learning Researcher in Astronomy and Astrophysics"

# Additional plugins
plugins:
  - jekyll-remote-theme  # Remote theme support plugin
