# Jekyll configuration file

# Use the Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"  # Correct GitHub repository for the theme

# Minimal Mistakes theme options
minimal_mistakes_skin: "dark"  # Choose a dark skin for an elegant, modern appearance
header: 
  image: "opo0432d.jpg"  # Set a header image (ensure the image exists in your assets or images directory)
  overlay_color: "#000"  # Dark overlay on the header image
  overlay_filter: 0.5  # Set the transparency for the overlay filter (0-1)

# Site settings
title: "Nitesh's Research"
description: "Machine Learning Researcher in Astronomy and Astrophysics"
baseurl: ""  # Leave empty if publishing to root domain (e.g., GitHub Pages)

# Custom navigation bar
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Updates"
    url: "/update/"
  - title: "My CV"
    url: "/Nitesh_CV.pdf"

# Social media links
author:
  name: "Nitesh Kumar"
  social:
    twitter: "astro_nitesh"
    facebook: "Nits874"
    github: "niteshchandra039"

# Theme settings
theme: minimal-mistakes-jekyll

# Additional plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag  # For better SEO
  - jekyll-sitemap  # Automatically generate sitemap
  - jekyll-include-cache  # Required for Minimal Mistakes theme

# SEO and Performance improvements
seo:
  type: "website"  # Website or blog
  author: "Nitesh Kumar"
  description: "Research in machine learning applications in astronomy."
